from enum import Enum

class EnforcementThreat(str, Enum):
    FALSE_POSITIVE = "FALSE_POSITIVE"
    FALSE_NEGATIVE = "FALSE_NEGATIVE"
    CASCADE_BLOCK = "CASCADE_BLOCK"
    RACE_CONDITION = "RACE_CONDITION"
    STALE_CONTEXT = "STALE_CONTEXT"
    PARTIAL_FAILURE = "PARTIAL_FAILURE"
    HUMAN_ERROR = "HUMAN_ERROR"
    POLICY_DRIFT = "POLICY_DRIFT"
    MODEL_DRIFT = "MODEL_DRIFT"
    INFRA_FAILURE = "INFRA_FAILURE"
    TENANT_WIDE_IMPACT = "TENANT_WIDE_IMPACT"
    IRREVERSIBLE_ACTION = "IRREVERSIBLE_ACTION"
    POLICY_CONFLICT = "POLICY_CONFLICT"

class ThreatSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
